services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "${RABBITMQ_PORT}:5672"
  
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
    driver: local