image:
  repository: rehive/spilo-11
  tag: 1.6.1
  pullPolicy: IfNotPresent
  init:
    command:
      - '/bin/sh'
    args:
      - '/launch.sh'
      - init
replicas: 1
debug: true
podAntiAffinity: soft
nodeSelector:
  cloud.google.com/gke-nodepool: postgres-pool
tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Equal
  value: postgres
resources: {}
bootstrapParameters:
  dcs:
    loop_wait: 70
    retry_timeout: 35
    ttl: 140
walE:
  enabled: true
  envDir: /home/postgres/etc/wal-e.d/env
  gcloudCredentials: google-credentials-postgres.json
  scheduleCronJob: 00 01 * * *
  retainBackups: 2
  s3Bucket:
  gcsBucket: {{cookiecutter.app_name}}-pgbackup
  backupThresholdMegabytes: 1024
  backupThresholdPercentage: 30
gcloudCredentials:
  enabled: true
  secretName: google-credentials-postgres
cloneWithWale:
  enabled: false
  cloneScope: patroni-{{cookiecutter.app_name}}-patroni
  cloneWalGcsBucket: {{cookiecutter.app_name}}-pgbackup
  gcloudCredentials: google-credentials-postgres.json
  cloneWaleEnvDir: /home/postgres/etc/clone-wal-e.d/env
persistentVolume:
  accessModes:
  - ReadWriteOnce
  annotations:
    app: spilo
    release: patroni-{{cookiecutter.app_name}}
  enabled: true
  size: 50Gi
  storageClass: patroni-standard
cleanup:
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/coreos/hyperkube
    tag: v1.8.4_coreos.0
rbac:
  create: true
serviceAccount:
  create: true
postgresParameters:
  bin_dir: /usr/lib/postgresql/13.0/bin
useConfigMaps: false
