# Default values for rehive-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 3
  resources:
    requests:
      memory: 350M
      cpu: 10m
    limits:
      memory: 750M
      cpu: 350m
  command: [gunicorn, --bind, 0.0.0.0:8000, --workers, '4', --worker-class, uvicorn.workers.UvicornH11Worker, --pythonpath, src, config.asgi:application]
  args: null
image:
  repository: {{ cookiecutter.docker_image_production }}
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: {{cookiecutter.app_name}}
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 10
ingress:
  enabled: false
postgres:
  enabled: true
  host: 172.26.144.2
  port: '5432'
  db: {{cookiecutter.app_name}}
  secret:
    key: postgres-password
    name: postgres
  user: {{cookiecutter.app_name}}
rabbitmq:
  enabled: false
  host: mini-yellow-goose.in.rmq2.cloudamqp.com
  user: scztisej
  vhost: scztisej
  port: 5672
  secret:
    name: rabbitmq
    key: rabbitmq-password
redis:
  enabled: false
  host: 172.26.145.11
  port: 6379
  secret:
    name: redis
    key: redis-password
workers:
  enabled: false