deployment:
  replicaCount: 1
  command: [gunicorn, --bind, 0.0.0.0:8000, --workers, '4', --worker-class, uvicorn.workers.UvicornH11Worker, --pythonpath, src, config.asgi:application]
  args: null
image:
  pullPolicy: IfNotPresent
  repository: {{ cookiecutter.docker_image_staging }}
  tag: latest
ingress:
  enabled: false
postgres:
  enabled: true
  host: 172.30.224.3
  port: 5432
  db: {{cookiecutter.app_name}}
  secret:
    key: postgres-password
    name: postgres
  user: {{cookiecutter.app_name}}
rabbitmq:
  enabled: true
  host: advanced-azure-ladybird.in.rmq2.cloudamqp.com
  user: sxclzvgq
  vhost: sxclzvgq
  port: 5672
  secret:
    name: rabbitmq
    key: rabbitmq-password
redis:
  enabled: true
  host: 172.30.225.3
  port: 6379
  secret:
    name: redis
    key: redis-password
service:
  externalPort: 80
  internalPort: 8000
  name: service-arb
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  type: ClusterIP
workers:
  enabled: true