deployment:
  command:
    - gunicorn
    - "config.wsgi:application"
  args:
    config: "file:config/gunicorn.py"
  replicaCount: 1
  resources: null
envFromSecret:
  enabled: true
  secretName: {{ cookiecutter.app_name }}
image:
  pullPolicy: IfNotPresent
  repository: {{ cookiecutter.docker_image_staging }}
  tag: latest
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  enabled: true
  hosts:
  - {{ cookiecutter.app_url_staging }}
  tls:
  - hosts:
    - {{ cookiecutter.app_url_staging }}
    secretName: {{cookiecutter.app_name}}-tls
postgres:
  enabled: true
  host: patroni-{{cookiecutter.app_name}}-patroni.{{cookiecutter.app_name}}-staging.svc.cluster.local
  port: 5432
  secret:
    key: password-admin
    name: patroni-{{cookiecutter.app_name}}-patroni
  user: webapp
rabbitmq:
  enabled: true
  host: rabbitmq-ha-{{cookiecutter.app_name}}.{{cookiecutter.app_name}}-staging.svc.cluster.local
  port: 5672
  secret:
    name: rabbitmq-ha-{{cookiecutter.app_name}}
    key: rabbitmq-password
service:
  externalPort: 80
  internalPort: 8000
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  name: nginx
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  type: NodePort
workers:
  enabled: false
  - name: worker-general
    internalPort: 8000
    replicaCount: 1
    command: "['celery', '-A', 'config.celery', 'worker', '--loglevel=INFO', '--concurrency=1', '--without-gossip', '--without-mingle', '--without-heartbeat', '-Q', 'general-{{cookiecutter.app_name}}']"
    resources: null
  - name: scheduler
    internalPort: 8000
    replicaCount: 1
    command: "['celery', '-A', 'config.celery', 'worker', '--beat', '--loglevel=INFO', '--pidfile=', '--concurrency=1','--without-gossip', '--without-mingle', '--without-heartbeat',  '-Q', 'scheduler-{{cookiecutter.app_name}}']"
    resources: null
