steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - pull
  - $_IMAGE:latest
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --cache-from
  - $_IMAGE:latest
  - --tag
  - $_IMAGE:$TAG_NAME
  - --tag
  - $_IMAGE:latest
  - --file
  - etc/docker/Dockerfile
  - .
images:
- $_IMAGE
