steps:
- name: gcr.io/kaniko-project/executor
  args:
  - --destination=$_IMAGE:$TAG_NAME
  - --destination=$_IMAGE:latest
  - --dockerfile=etc/docker/Dockerfile
  - --cache=true
  - --cache-ttl=336h0m0s
